[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "equal"
path = "equal.rs"

[[bin]]
name = "get-info"
path = "get-info.rs"

[dependencies]
glalby = { path = "../" }

[build-dependencies]

[dev-dependencies]
