[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "get-info"
path = "get-info.rs"

[[bin]]
name = "make-invoice"
path = "make-invoice.rs"

[dependencies]
glalby = { path = "../" }
rand = "*"

[build-dependencies]

[dev-dependencies]
