name: Build libraries for all targets

on:
  workflow_call:
    inputs:
      rust_version:
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        build: [
          { host: ubuntu-20.04, tool: cargo, target: x86_64-unknown-linux-gnu,    output: libglalby_bindings.so },
          { host: ubuntu-20.04, tool: cross, target: arm-unknown-linux-gnueabihf, output: libglalby_bindings.so },
          { host: windows-2019, tool: cargo, target: x86_64-pc-windows-msvc,      output: glalby_bindings.dll },
          { host: macos-12,     tool: cargo, target: x86_64-apple-darwin,         output: libglalby_bindings.dylib },
          { host: macos-12,     tool: cargo, target: aarch64-apple-darwin,        output: libglalby_bindings.dylib },
        ]
    runs-on: ${{ matrix.build.host }}
    steps:
      - name: Set up Rust
        run: |
          rustup toolchain install ${{ inputs.rust_version }}
          rustup default ${{ inputs.rust_version }}

      - name: Add target
        if: ${{ matrix.build.tool == 'cargo' }}
        run: rustup target add ${{ matrix.build.target }}

      - name: Install cross
        if: ${{ matrix.build.tool == 'cross' }}
        run: cargo install cross --git https://github.com/cross-rs/cross --rev c87a52a

      - name: Install Protoc
        if: ${{ matrix.build.tool == 'cargo' }}
        shell: bash
        run: |
          export PB_REL=https://github.com/protocolbuffers/protobuf/releases
          curl -LO $PB_REL/download/v25.3/protoc-25.3-linux-x86_64.zip
          mkdir protoc
          unzip protoc-25.3-linux-x86_64.zip -d protoc
          sudo mv protoc/bin/protoc /usr/local/bin/protoc

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ${{ matrix.build.tool }} build --release --target ${{ matrix.build.target }}

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: glalby-bindings-${{ matrix.build.target }}
          path: target/${{ matrix.build.target }}/release/${{ matrix.build.output }}

  make-macos-universal:
    runs-on: macos-12
    needs: build
    steps:
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: glalby-bindings-x86_64-apple-darwin
          path: x86_64-apple-darwin

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: glalby-bindings-aarch64-apple-darwin
          path: aarch64-apple-darwin

      - name: Make universal library
        run: |
          lipo -create -output "libglalby_bindings.dylib" "x86_64-apple-darwin/libglalby_bindings.dylib" "aarch64-apple-darwin/libglalby_bindings.dylib"

      - name: Archive universal library
        uses: actions/upload-artifact@v4
        with:
          name: glalby-bindings-universal-apple-darwin
          path: libglalby_bindings.dylib
